modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasLibrary.png"
license="Restricted"

[[mods]]
modId="hellaslibrary"
version="1.0.0"
displayName="HellasLibrary"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellaslibrary]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellaslibrary]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellaslibrary]]
modId="hellascontrol"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"